### ISSUE TITLE
Question: Since .NET Standard 2.0 - this should be able to run on Xamarin

### ISSUE THREAD

**Issue by dlandi** [yallie/Zyanea#3]
Hi Yallie, I am very excited to find this library supporting Zero Proof of Knowledge password management.  Can't wait to try it.  

Question: Since this support .NET Standard 2.0; and since the new Xamarin platform support Standard 2.0, then I should be able to use this library, as is, in Xamarin.

Thoughts?

-dennis

**Comment by yallie** [comment]
Hi Dennis, most likely yes, this should run on Xamarin Android (but perhaps not on iOS due to runtime code generation restrictions). Please be aware that this library is currently not used in production anywhere, it's more like proof of concept. Also, I'm not particularly satisfied with its SRP implementation.

I've recently made a library that [implements SRP-6a protocol](https://github.com/secure-remote-password/srp.net) in a standard way, interoperable with other libraries and RFC5054-compliant, with an easy API. It supports .NET Standard as well and I'm pretty sure it should run on Xamarin, both iOS and Android. But that's only the authentication protocol, not the complete RPC solution like Zyan/Zyanea. Still might be worth looking at.

**Comment by dlandi** [comment]
Thanks yallie, looking at your SRP implementation now...
